# Use an official Node runtime as a parent image
FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
COPY . .

RUN npm i

EXPOSE 5000

CMD ["npm", "run", "dev", "--" ,"-p", "5000"]